export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const CATEGORY_LIST_FETCHED='CATEGORY_LIST_FETCHED';

export const POST_FETCHED='POST_FETCHED';
export const POST_CREATED='POST_CREATED';